name: Latest Web Development Tricks Workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * SUN'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://matrixread.com/webdev/feed"
          max_post_count: 100  
